apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: still-planarian-go 
  janus-idp.io/tekton: still-planarian-go
  backstage.io/kubernetes-id: still-planarian-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: still-planarian-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  